<?php

return [
	'seo:autogen' => 'Autogenerate entity SEO',
	'seo:autogen:count' => 'SEO data has been autogenerated for %s of %s entities',
	'seo:edit' => 'Edit page SEO',
	'seo:path' => 'Original Path',
	'seo:paths' => 'Leading Paths',
	'seo:sef_path' => 'Target Path',
	'seo:sef_path:help' => 'Path without the domain with an opening forward slash, e.g. /file/sef-file-url',
	'seo:title' => 'Page Title',
	'seo:description' => 'Page Description',
	'seo:keywords' => 'Page Keywords',
	'seo:metatags' => 'Page Metatags',
	'seo:edit:success' => 'Page data has been saved successfully',
	'seo:edit:error' => 'Page data could not be saved',
	'seo:search:path' => 'URL or path',
	'seo:edit:not_unique' => 'Target path must be unique, there is already another rewrite rule with this SEF path',
	
	'seo:object' => 'Articles',
	'seo:settings:edit:help' => '
		Only enter title, description and keywords information, if you would like them to be permanently replaced, otherwise leave empty.
		Metatags will be filtered, so that that other plugins can populate relevant tags - the ones you enter here, may be overwritten.
	',
	'seo:settings:patterns:help' => '
		Below, you can configure SEF rewrite rules for various entity types.
		Patterns can include the following variables:
		  - <b>{guid}</b>: entity GUID
		  - <b>{title}</b>: entity title
		  - <b>{username}</b>: username
		  - <b>{timestamp}</b>: created timestamp
		  - <b>{date}</b>: created date

        Leave the field empty, if you don\'t want the URLs to be rewritten for the given entity type.
	',

	'menu:page:header:seo' => 'Search engine optimization',
	'admin:seo' => 'Search engine optimization',
	'admin:seo:settings' => 'Settings',
	'admin:seo:rules' => 'Rewrite Rules',
	'seo:delete:success' => 'Rule has been deleted',
	'seo:delete:error' => 'Rule could not been deleted',

	'seo:autogen:intro' => 'This script will help you to autogenerate SEF URLs for site content and users. Please configure your rewrite patterns in plugin settings before proceeding',
	'seo:autogen:item_count' => 'Your site has <b>%s</b> entities. Generator script might take a while to complete',
	'seo:autogen:success_count' => 'Processed: ',
	'seo:autogen:error_count' => 'Errors: ',

];
